### ISSUE TITLE
Versioning the documentation

### ISSUE THREAD

**Issue by mehmetmuejde** [scikit-activeml/scikit-activeml#182] opened 2021-10-28 13:18 UTC

**Comment by mmuejde** [comment] 2021-11-10 10:54
https://sphinxcontrib-versioning.readthedocs.io/en/latest/tutorial.html

**Comment by mmuejde** [comment] 2021-11-10 10:55
https://holzhaus.github.io/sphinx-multiversion/master/index.html

**Comment by mmuejde** [comment] 2021-11-10 10:55
https://github.com/Smile-SA/sphinx-versions

**Comment by mmuejde** [comment] 2021-12-01 15:22
Custom solution?

**Comment by mherde** [comment] 2023-06-07 13:31
Duplicate of issue #305

**Closed as completed by mherde** 2023-06-07 13:31 UTC
Labels: documentation
