### ISSUE TITLE
BUG: SklearnRegressor with Skorch ValueError: shape mismatch

### ISSUE THREAD

**Issue by meeen** [scikit-activeml/scikit-activeml#407] opened 2024-06-17 21:48 UTC
### Describe the issue:

Hello,

I want to use Active learning for Regression with my Pytorch neural network, for that reason I use Skorch to make at sklearn compatible and SklearnRegressor. If I use my Code code with RandomForestRegressor there is no Error. When I train the network without Active Learning just with Skorch there is no problem. 

### Reproduce the bug via a code example:

```python
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.layer1 = nn.Linear(4, 64)
        self.layer2 = nn.Linear(64, 16)
        self.layer3 = nn.Linear(16, 8)
        self.output_layer = nn.Linear(8, 1)

    def forward(self, x):
        x = nn.ReLU()(self.layer1(x))
        x = nn.ReLU()(self.layer2(x))
        x = nn.ReLU()(self.layer3(x))
        x = self.output_layer(x)
        return x

net = NeuralNetRegressor(
    MyModel,
    max_epochs=198,         # Number of epochs to train
    lr=0.001,              # Learning rate
    optimizer=optim.Adam,  # Type of optimizer to use
    criterion=nn.MSELoss,  # Loss function
    batch_size=1,  # Smaller batch size for more updates
    iterator_train__shuffle=False,
    #warm_start =True
)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_scaled, test_size=0.2, shuffle=False)

n_initial = 5
initial_idx = np.random.choice(range(len(X_train)), size=n_initial, replace=False)
y = np.full(shape=y_train.shape, fill_value=MISSING_LABEL)
y[[initial_idx]] = y_train[[initial_idx]].astype(np.float32)

qs = ExpectedModelChangeMaximization()
reg = SklearnRegressor(estimator= net,missing_label=MISSING_LABEL)

reg.fit(X_train, y)

n_cycles = 5
for c in range(n_cycles):
    query_idx = qs.query(X=X_train, y=y, reg=reg)
    y[[query_idx]] = y_train[[query_idx]].astype(np.float32)
reg.fit(X_train, y)
reg.score(X_test,y_test)
```

### Error message:

```shell
ValueError                                Traceback (most recent call last)
Cell In[235], line 5
      1 n_cycles = 5
      3 for c in range(n_cycles):
----> 5     query_idx = qs.query(X=X_train, y=y, reg=reg)
      7     y[[query_idx]] = y_train[[query_idx]].astype(np.float32)

File ~\AppData\Roaming\Python\Python310\site-packages\skactiveml\pool\_expected_model_change_maximization.py:179, in ExpectedModelChangeMaximization.query(self, X, y, reg, fit_reg, sample_weight, candidates, batch_size, return_utilities)
    177 else:
    178     utilities = np.full(len(X), np.nan)
--> 179     utilities[mapping] = utilities_cand
    181 return simple_batch(
    182     utilities,
    183     self.random_state_,
    184     batch_size=batch_size,
    185     return_utilities=return_utilities,
    186 )

ValueError: shape mismatch: value array of shape (119,119) could not be broadcast to indexing result of shape (119,)
```

### Context for the issue:

It's part of my thesis and an ongoing research project, I want to select data points of very time-consuming simulations and experiments in the context of manufacturing. Working Active Learning could cut cost and time by more than 80%

**Comment by mherde** [comment] 2024-06-18 11:15
Hello @meeen

Thanks for your interest in using `scikit-activeml`. The exception is caused by a shape mismatch between `skorch` and `scikit-learn` estimators. The latter expects targets of the shape `(n_samples,)`, while the `NeuralNetRegressor` requires `(n_samples, 1)`. We overcome this issue by adding a small helper class, `SkorchRegressor,` overriding the `fit` and `predict` methods of the `NeuralNetRegressor.` Currently, we are also developing dedicated wrapper classes for `skorch` to resolve such issues in the future. Below, you find the code snippet (including comments as explanations) that we used for testing. 

```python
import matplotlib.pyplot as plt
import numpy as np

from sklearn.model_selection import train_test_split
from torch import nn
from skactiveml.pool import ExpectedModelChangeMaximization
from skactiveml.regressor import SklearnRegressor
from skactiveml.utils import is_labeled
from skorch import NeuralNetRegressor
from torch import optim

# Use np.nan in case of regression because numeric values as missing labels
# may be ambiguous in regression.
MISSING_LABEL = np.nan

# Create toy regression dataset.
n_samples = 200
X_scaled = np.random.uniform(-2, 2, n_samples)
y_scaled = X_scaled**2 + np.random.uniform(-0.1, 0.1, n_samples)
X_scaled = X_scaled.astype(np.float32).reshape(-1, 1)

print(y_scaled.shape)

# Regression module for toy dataset with one-dimensional input data.
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.layer1 = nn.Linear(1, 64)
        self.layer2 = nn.Linear(64, 16)
        self.layer3 = nn.Linear(16, 8)
        self.output_layer = nn.Linear(8, 1)

    def forward(self, x):
        x = nn.ReLU()(self.layer1(x))
        x = nn.ReLU()(self.layer2(x))
        x = nn.ReLU()(self.layer3(x))
        x = self.output_layer(x)
        return x

# Helper class for reshaping targets according to scikit-learn convention.
class SkorchRegressor(NeuralNetRegressor):

    def fit(self, X, y, **fit_params):
        if y.ndim == 1:
            y = y.reshape(-1, 1)
        return super().fit(X, y)

    def predict(self, X):
        y_pred = super().predict(X)
        if y_pred.ndim == 2:
            y_pred = y_pred.ravel()
        return y_pred

# Create network using the helper class.
net = SkorchRegressor(
    MyModel,
    max_epochs=50,  # Number of epochs to train
    lr=0.1,  # Learning rate
    optimizer=optim.RAdam,  # Type of optimizer to use
    criterion=nn.MSELoss,  # Loss function
    batch_size=8,  # Smaller batch size for more updates
    iterator_train__shuffle=True,
    verbose=False,
)

# Wrap network using wrapper from skactiveml.
reg = SklearnRegressor(
    estimator=net, missing_label=MISSING_LABEL, random_state=0
)

# Split train and test data.
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_scaled, test_size=0.2, shuffle=False
)

# Define array of initially labeled samples.
n_initial = 20
initial_idx = np.random.choice(
    range(len(X_train)), size=n_initial, replace=False
)
y = np.full(shape=y_train.shape, fill_value=MISSING_LABEL).astype(
    np.float32
)
y[initial_idx] = y_train[initial_idx]

# Setup query strategy, originally designed for linear regression models.
qs = ExpectedModelChangeMaximization()

# Perform active learning cycle.
n_cycles = 5
utilities = None
for c in range(n_cycles):
    query_idx, utilities = qs.query(
        X=X_train, y=y, reg=reg, return_utilities=True, batch_size=4
    )
    y[query_idx] = y_train[query_idx]

# Visualize results after last cycle.
reg = reg.fit(X_train, y)
y_pred = reg.predict(X_scaled)
is_lbld = is_labeled(y, missing_label=MISSING_LABEL)
plt.scatter(X_train[is_lbld][:, 0], y_train[is_lbld], label="labeled")
if utilities is not None:
    plt.scatter(X_train, utilities[0], label="utilities")
plt.scatter(X_scaled.ravel(), y_pred, label="predictions")
plt.title(f"Score: {reg.score(X_test, y_test)}")
plt.legend()
plt.show()
```


I hope that answers your question and is helpful for evaluations. If yes, feel free to close this issue. Otherwise, please ask further questions, and we will reply much faster to them.

Best regards

@tpham93  and @mherde

**Comment by meeen** [comment] 2024-06-19 20:23
Thanks for your fast help :) Works very well

**Comment by meeen** [comment] 2024-06-19 20:23
Thanks for your fast help :) Works very well

**Closed** 2024-06-19 20:23 UTC
