### ISSUE TITLE
Restructure tests such that tests for common arguments (missing_label, classes, etc.) are inherited via an abstract test class

### ISSUE THREAD

**Issue by tpham93** [scikit-activeml/scikit-activeml#230] opened 2022-04-27 13:21 UTC

**Comment by mherde** [comment] 2023-05-23 10:59
The following sub-packages must be restructured according to the new test design:
- [x] `pool`,
- [ ] `stream`,
  - [ ] query strategies,
  - [ ] budget managers,
- [ ] `classifier`,
- [ ] `regressor`.

**Comment by mherde** [comment] 2023-06-07 13:21
Duplicate of #303

**Closed by mherde** 2023-06-07 13:21 UTC
